Project 1 - Wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("search/", views.search, name="search"),
    path("random/", views.random_page, name="random_page"),
    path("editor/", views.page_editor, name="page_editor"),
    path("editor/<str:title>", views.page_editor, name="edit"),
    path("<str:title>", views.read_entry, name="read_entry")
]

Project 1 - Wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

Project 1 - Wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

Project 1 - Wiki/encyclopedia/views.py
# Imports Section
# --- Django Related Imports ---
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

# --- UTILS ---
from . import util

# --- MISC ---
from markdown2 import markdown
import random
import re

# Forms
class EntryForm(forms.Form):
    title = forms.CharField(label="", max_length=50, widget=forms.TextInput(attrs={'placeholder': 'Title goes here...'}))
    content = forms.CharField(label="", widget=forms.Textarea(attrs={'placeholder': 'Content goes here...'}))


# Views Definition Section

def index(request):
    """
    Home Page
    Returns a page containing all entries in the encyclopedia
    """
    entries = util.list_entries()
    return render(request, "encyclopedia/index.html", {
        "entries": entries
    })

def read_entry(request, title: str):
    """
    Entry Page
    Returns the html version of the .md file named :title:
    Returns the 404 page if file not found
    """
    entry = util.get_entry(title)
    if entry:
        title = title.capitalize()
        entry_html = markdown(entry)
        return render(request, "encyclopedia/entry_page.html", {
            "title": title,
            "entry_html": entry_html
        })
    else:
        return render(request, "encyclopedia/404_page.html", {
            "title": title
        })
    
def search(request):
    """
    Search Page
    Returns the full match page of the query if found
    Returns the relevant partial matches for the given query, if it is not a full match
    Returns the homepage for an empty query, otherwise
    """
    query = request.GET.get('q')
    if query != "":
        page = util.get_entry(query)
        if page:
            title = query.capitalize()
            entry_html = markdown(page)
            return render(request, "encyclopedia/entry_page.html", {"title": title, "entry_html": entry_html})
        else:
            entries = util.list_entries()
            relevant_entries = []
            for entry in entries:
                if re.search(query, entry, re.IGNORECASE):
                    relevant_entries.append(entry)
            return render(request, "encyclopedia/search.html", {"entries": relevant_entries})
    else:
        entries = util.list_entries()
        return render(request, "encyclopedia/index.html", {"entries": entries})

def random_page(request):
    """
    Random Page
    Returns a random entry page
    """
    entries = util.list_entries()
    return read_entry(request, random.choice(entries))

def page_editor(request, title=""):
    """
    Editor (Add/Edit) Page
    Returns a page where the user can add/edit an entry
    """
    if request.method == "POST":
        form = EntryForm(request.POST)
        if form.is_valid():

            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            util.save_entry(title, content)

            return HttpResponseRedirect(reverse('encyclopedia:read_entry', args=[title]))
    else:
        if title == "":
            form = EntryForm()
        else:
            content = util.get_entry(title)
            form = EntryForm(initial={"title": title, "content":content})
    return render(request, "encyclopedia/entry_editor.html", {"form":form})

Project 1 - Wiki/encyclopedia/templates/encyclopedia/404_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>404 Error</h1>
    <p>Requested entry: {{title}} - was not found in our encyclopedia.</p>
    <p>Be the first one to write it ...</p>
{% endblock %}

Project 1 - Wiki/encyclopedia/templates/encyclopedia/entry_editor.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia Editor
{% endblock %}

{% block body %}
    <h1>Write & Edit your Page Below:</h1>
    <form action="{% url 'encyclopedia:page_editor' %}" method="POST">
        {% csrf_token %}
        {{form}}
        <input type=submit value="Submit Entry">
    </form>
{% endblock %}

Project 1 - Wiki/encyclopedia/templates/encyclopedia/entry_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    {{ entry_html|safe }}
    <a href="{% url 'encyclopedia:edit' title=title %}">Edit Page</a>
{% endblock %}

Project 1 - Wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li>{{ entry }}</li>
        {% endfor %}
    </ul>

{% endblock %}

Project 1 - Wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="GET">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:page_editor' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random_page' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

Project 1 - Wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia Search Results
{% endblock %}

{% block body %}
    <h1>Relevant Search Results:</h1>

    {% if entries %}

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:read_entry' title=entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

    {% else %}
    <p>No matching results found!</p>
    {% endif %}

{% endblock %}